import { sampleManifest } from './sample-manifest.mjs';
import { createPromptModel, adaptPrompt, createCharacterSheetModel, buildCharacterSheetPrompt } from './prompt-builder.mjs';
import { put, getAll, remove, exportData, importData } from './storage.mjs';

const state = { model: createPromptModel(), step: 0, result: '', history: [], charFlow: false, charStep: 0, characterSheet: createCharacterSheetModel() };
const steps = ['subject', 'style', 'composition', 'lighting', 'adjustment', 'textEnabled', 'textContent', 'textStyle', 'textLayout', 'textPosition', 'textSize', 'adapter', 'result'];
const stepLabels = ['イメージ', '絵柄', '構図', '光・雰囲気', '微調整', '文字', '出力先', '完成'];
const textStyleLabels = { simple: 'シンプル', bold: '力強い', elegant: '上品', cute: 'かわいい', handwritten: '手書き風', retro: 'レトロ', pop: 'ポップ', futuristic: '未来的' };
const textLayoutLabels = { 'center-large': '中央に大きく', 'top-title': '上部タイトル', 'bottom-title': '下部タイトル', 'left-aligned': '左寄せ', vertical: '縦書き', diagonal: '斜め', arch: 'アーチ', dynamic: 'ダイナミック' };
const outfitLabels = { casual: 'カジュアル', smart: 'きれいめ', sporty: 'スポーティ', outer: 'アウター', uniform: '制服', summer: '夏服', winter: '冬服', unique: '個性的' };
const outfitIds = Object.keys(outfitLabels);
const sceneryCompositionLabels = { closeup: 'アップ', near: '近景', standard: '標準', wide: '広角', panorama: '大パノラマ' };
const sceneryCompositionDescriptions = { closeup: '細部を大きく見せる', near: '主役を大きく見せる', standard: '周囲とバランスよく見せる', wide: '周囲の景色まで広く見せる', panorama: '景観全体を大きく見せる' };
const flowCategories = [{ label: 'イメージ', index: 0 }, { label: '絵柄', index: 1 }, { label: '構図', index: 2 }, { label: '光・雰囲気', index: 3 }, { label: '微調整', index: 4 }, { label: '文字', index: 5 }, { label: '出力先', index: 11 }, { label: '完成', index: 12 }];
const positionLabels = { 'top-left': '左上', 'top-center': '上', 'top-right': '右上', 'center-left': '左', center: '中央', 'center-right': '右', 'bottom-left': '左下', 'bottom-center': '下', 'bottom-right': '右下' };
const sizeLabels = { small: '小さめ', medium: '標準', large: '大きめ' };
const $ = (selector) => document.querySelector(selector);
const app = $('#app');
const escapeHtml = (value) => String(value).replace(/[&<>'\"]/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' }[char]));
const sampleLabel = (category, id) => ({ style: { anime: 'アニメ風', illustration: 'イラスト風', realistic: 'リアル風', 'manga-lineart': 'マンガ風（線画）', watercolor: '水彩風', 'oil-painting': '油彩風', 'simple-flat': 'シンプル・フラット', 'pop-cute': 'ポップ・かわいい' }, composition: { 'face-closeup': '顔アップ', 'bust-up': 'バストアップ', 'upper-body': '上半身', 'full-body': '全身', 'wide-shot': '引き', 'side-view': '横から', 'low-angle': 'ローアングル', 'high-angle': '俯瞰（上から）' }, lighting: { 'natural-light': '自然光', bright: '明るい', 'soft-light': '柔らかい', sunset: '夕暮れ', night: '夜', cinematic: 'シネマティック', dreamy: '幻想的', dramatic: 'ドラマチック' } }[category][id] || id);

function render() {
  if (state.charFlow) return renderCharacterFlow();
  const step = steps[state.step];
  const headings = { subject: '想像しているイメージを、<br>かたちにしよう。', style: 'どんな絵にする？', composition: 'どこまで見せる？', lighting: 'どんな空気感にする？', adjustment: '細かい印象を整える', textEnabled: '画像に文字を入れますか？', textContent: '入れたい文字', textStyle: '文字の雰囲気', textLayout: '文字レイアウト', textPosition: '文字の位置', textSize: '文字の大きさ', adapter: 'どの画像生成AIで使いますか？' };
  const category = flowCategories.findIndex((item) => state.step >= item.index && (flowCategories[flowCategories.indexOf(item) + 1]?.index ?? steps.length) > state.step);
  app.innerHTML = `<main class="shell"><header class="topbar"><a class="brand" href="./" aria-label="ホームへ"><span class="brand-mark">P</span><span><strong>Prompt Studio</strong><small>Image Prompt Maker</small></span></a><span class="eyebrow">VER.2 / LOCAL FIRST</span></header><div class="progress" aria-label="作成ステップ">${flowCategories.map((item, index) => `<button type="button" class="progress-item ${index === category ? 'current' : ''} ${index < category ? 'done' : ''}" data-flow-step="${item.index}" ${index === category ? 'aria-current="step"' : ''}><b>${index + 1}</b>${item.label}</button>`).join('<i aria-hidden="true">—</i>')}</div><header class="page-heading"><p class="kicker">${state.step === 0 ? 'YOUR IDEA' : step === 'result' ? 'COMPLETE' : flowCategories[category]?.label || ''}</p><h1>${step === 'result' ? 'プロンプトが完成しました。' : headings[step]}</h1><p class="lead">${state.step === 0 ? '好きな要素を選ぶだけで、画像生成AIに伝わるプロンプトを作れます。' : step === 'result' ? '選んだイメージから、すぐに使える文章に整えました。' : '見て選ぶだけで大丈夫。あとから戻って変更できます。'}</p></header><section id="screen" aria-live="polite"></section><nav class="nav"><button class="secondary" id="back" ${state.step === 0 ? 'disabled' : ''}>← 戻る</button><button class="primary" id="next">${state.step === steps.length - 1 ? 'もう一度つくる' : '次へ →'}</button></nav></main>`;
  const screen = $('#screen');
  if (step === 'subject') screen.innerHTML = `<div class="subject-card"><label for="subject">まず、作りたいものを教えてください。</label><textarea id="subject" placeholder="例：海辺を歩いている女の子、夕暮れのカフェで本を読む男性">${escapeHtml(state.model.subject)}</textarea><p class="hint">専門的なプロンプトは必要ありません。</p></div><div class="idea-note"><span>01</span><div><strong>イメージから始める</strong><p>次の画面から、好きな絵柄・構図・光を選びます。</p></div></div><div class="character-entry"><p><strong>人物を入れますか？</strong></p><div class="choice-grid"><button class="choice ${state.model.characterUsage === 'with-character' ? 'selected' : ''}" data-character-usage="with-character">人物あり<small>人物やキャラクターが登場する画像</small></button><button class="choice ${state.model.characterUsage !== 'with-character' ? 'selected' : ''}" data-character-usage="without-character">人物なし<small>風景・建物・食べ物・商品など</small></button></div><div class="character-entry-options" ${state.model.characterUsage === 'with-character' ? '' : 'hidden'}><p><strong>人物の設定</strong></p><button class="choice ${state.model.characterMode === 'free-character' ? 'selected' : ''}" data-character-mode="free-character">キャラクターを固定しない</button><button class="choice ${state.model.characterMode === 'character-sheet' ? 'selected' : ''}" data-character-mode="character-sheet">キャラクターシートを使う</button><p class="hint">同じキャラクターを使う場合は、作成したキャラクターシート画像を参考画像として一緒に使用してください。</p><div class="outfit-inline"><p><strong>今回の服装</strong></p><div class="choice-grid"><button class="choice ${!state.model.outfitStyle ? 'selected' : ''}" data-outfit-style="">変更しない</button>${outfitIds.map((id) => `<button class="choice ${state.model.outfitStyle === id ? 'selected' : ''}" data-outfit-style="${id}">${outfitLabels[id]}</button>`).join('')}</div><p class="hint">服装を選ぶと、今回の画像だけ服装を変更します。</p></div></div></div>`;
  if (['style', 'composition', 'lighting'].includes(step)) screen.innerHTML = `<h2>${step === 'style' ? 'どんな絵にする？' : step === 'composition' ? 'どこまで見せる？' : 'どんな空気感にする？'}</h2><div class="cards">${sampleManifest.filter((x) => x.category === step).map((item) => `<button class="card ${state.model[step] === item.id ? 'selected' : ''}" data-id="${item.id}"><img src="${item.image}" alt="${item.alt}"><span>${item.label}</span></button>`).join('')}</div>`;
  if (step === 'subject' && state.model.characterUsage === 'with-character') { const inline = screen.querySelector('.outfit-inline'); if (inline) inline.innerHTML = `<p><strong>今回の服装</strong></p><button class="choice outfit-keep ${!state.model.outfitStyle ? 'selected' : ''}" data-outfit-style="">変更しない<small>現在の人物設定の服装をそのまま使用</small></button><p><strong>服装を変える</strong></p><div class="text-layout-grid outfit-grid">${outfitIds.map((id) => `<button class="text-layout-card ${state.model.outfitStyle === id ? 'selected' : ''}" data-outfit-style="${id}"><img src="./images/samples/outfit/female/${id}.png" alt="${outfitLabels[id]}の服装参考"><span>${outfitLabels[id]}</span></button>`).join('')}</div><p class="hint">画像は服装の雰囲気の参考です。人物設定は変わりません。</p>`; }
  if (step === 'composition' && state.model.characterUsage === 'without-character') screen.innerHTML = `<h2>どこまで見せる？</h2><p class="layout-lead">同じ場所を、見せる広さで選びます。</p><div class="text-layout-grid scenery-grid">${Object.entries(sceneryCompositionLabels).map(([id, label]) => `<button class="text-layout-card ${state.model.sceneryComposition === id ? 'selected' : ''}" data-scenery-composition="${id}"><img src="./images/samples/scenery-composition/${id}.png" alt="${label}の風景構図参考"><span>${label}</span><small>${sceneryCompositionDescriptions[id]}</small></button>`).join('')}</div>`;
  if (step === 'adjustment') screen.innerHTML = `<h2>もう少しだけ調整する？</h2><p class="beginner-note">迷ったら中央のままでOKです。</p>${[['detail','描き込み量','シンプル','細かく描く'],['color','色の鮮やかさ','落ち着いた色','鮮やかな色'],['background','背景の情報量','すっきり','背景もしっかり'],['mood','雰囲気の強さ','自然','印象的']].map(([key,label,left,right]) => `<label class="range-label"><span><strong>${label}</strong><small>${left} ← → ${right}</small></span><input aria-label="${label}" data-adjustment="${key}" type="range" min="0" max="4" value="${state.model.adjustments[key]}"></label>`).join('')}<fieldset><legend>入れたくないもの</legend>${[['text','文字'],['logo','ロゴ'],['watermark','透かし'],['extra-objects','余計な物'],['clutter','ごちゃごちゃした背景'],['distortion','形の崩れ']].map(([id,label]) => `<label class="chip"><input type="checkbox" data-negative="${id}" ${state.model.negative.includes(id) && !(state.model.textOverlay.enabled && id === 'text') ? 'checked' : ''} ${state.model.textOverlay.enabled && id === 'text' ? 'disabled' : ''}> ${label}</label>`).join('')}</fieldset>`;
  if (step === 'textEnabled') screen.innerHTML = `<h2>画像に文字を入れますか？</h2><p>必要なときだけ設定できます。</p><div class="adapter-list"><button class="choice ${!state.model.textOverlay.enabled ? 'selected' : ''}" data-text-enabled="false">入れない</button><button class="choice ${state.model.textOverlay.enabled ? 'selected' : ''}" data-text-enabled="true">文字を入れる</button></div>`;
  if (step === 'textContent') screen.innerHTML = `<h2>入れたい文字</h2><textarea id="text-content" placeholder="例：夏の思い出、SALE">${escapeHtml(state.model.textOverlay.content)}</textarea>`;
  if (step === 'textStyle') screen.innerHTML = `<h2>文字の雰囲気</h2><p class="layout-lead">仕上がりを見ながら選べます。あとから戻って変更できます。</p><div class="text-layout-grid text-mood-grid">${Object.entries(textStyleLabels).map(([id,label]) => `<button class="text-layout-card ${state.model.textOverlay.style === id ? 'selected' : ''}" data-text-style="${id}"><img src="./images/samples/text-mood/${id}.png" alt="${label}の文字の雰囲気例"><span>${label}</span></button>`).join('')}</div>`;
  if (step === 'textLayout') screen.innerHTML = `<h2>文字のレイアウト</h2><p class="layout-lead">配置の見本から選びます。文字の雰囲気は前の設定が引き継がれます。</p><div class="text-layout-grid">${Object.entries(textLayoutLabels).map(([id,label]) => `<button class="text-layout-card ${state.model.textOverlay.layout === id ? 'selected' : ''}" data-text-layout="${id}"><img src="./images/samples/text-layout/${id}.png" alt="${label}の文字レイアウト例"><span>${label}</span></button>`).join('')}</div>`;
  if (step === 'textPosition') screen.innerHTML = `<h2>文字の位置</h2><div class="position-grid">${Object.entries(positionLabels).map(([id,label]) => `<button class="choice ${state.model.textOverlay.position === id ? 'selected' : ''}" data-text-position="${id}">${label}</button>`).join('')}</div>`;
  if (step === 'textSize') screen.innerHTML = `<h2>文字の大きさ</h2><div class="choice-grid">${Object.entries(sizeLabels).map(([id,label]) => `<button class="choice ${state.model.textOverlay.size === id ? 'selected' : ''}" data-text-size="${id}">${label}</button>`).join('')}</div><label class="chip"><input type="checkbox" data-avoid-overlap ${state.model.textOverlay.avoidSubjectOverlap ? 'checked' : ''}> 人物・主役に文字を重ねない</label>`;
  if (step === 'adapter') screen.innerHTML = `<h2>どの画像生成AIで使いますか？</h2><div class="adapter-list">${[['generic','その他の画像生成AI','汎用プロンプト'],['chatgpt','ChatGPT','ChatGPTの画像生成向け'],['gemini','Gemini','Geminiの画像生成向け']].map(([id,label,desc]) => `<button aria-label="${label}" class="adapter ${state.model.adapter === id ? 'selected' : ''}" data-adapter="${id}"><strong>${label}</strong><small>${desc}</small></button>`).join('')}</div>`;
  if (step === 'result') screen.innerHTML = `<div class="result-layout"><div class="result-copy"><label for="result">完成したPrompt</label><textarea id="result" readonly>${escapeHtml(state.result)}</textarea><button class="copy-cta" id="copy">◎ コピーする</button><div class="result-actions"><button id="save">保存</button><button id="backup">JSONバックアップ</button><input id="restore" type="file" accept="application/json"></div></div></div><div class="selection-summary"><span>絵柄：${sampleLabel('style', state.model.style)}</span><span>構図：${sampleLabel('composition', state.model.composition)}</span><span>光：${sampleLabel('lighting', state.model.lighting)}</span><span>出力：${state.model.adapter === 'generic' ? 'その他の画像生成AI' : state.model.adapter === 'chatgpt' ? 'ChatGPT' : 'Gemini'}</span></div><div class="history"><h2>最近の履歴</h2>${state.history.map((item) => `<p>${new Date(item.createdAt).toLocaleString()}<br>${escapeHtml(item.prompt.slice(0, 100))}<br><button class="favorite" data-favorite="${item.id}">${item.favorite ? 'お気に入り済み' : 'お気に入り'}</button></p>`).join('') || '<p>まだ履歴はありません。</p>'}</div>`;
  if (step === 'subject') { const hint = screen.querySelector('.subject-card .hint'); if (hint) hint.insertAdjacentHTML('afterend', '<div class="subject-guidance"><strong>少し具体的に書くと、イメージに近づきます。</strong><p>例：</p><ul><li>「お寺」→「夜のお寺を歩く着物姿の女性」</li><li>「海」→「夕暮れの海辺を歩く親子」</li><li>「カフェ」→「窓際でコーヒーを飲む男性」</li></ul></div>'); }
  bind();
}

function renderCharacterFlow() {
  const outfitLabels = { casual: 'カジュアル', smart: 'きれいめ', sporty: 'スポーティ', outer: 'アウター', uniform: '制服', summer: '夏服', winter: '冬服', unique: '個性的' };
  const outfitIds = Object.keys(outfitLabels);
  const outfitCards = (type) => type === 'unspecified'
    ? `<div class="choice-grid">${outfitIds.map((id) => `<button class="choice ${state.characterSheet.outfitStyle === id ? 'selected' : ''}" data-outfit-style="${id}">${outfitLabels[id]}</button>`).join('')}</div>`
    : `<div class="text-layout-grid outfit-grid">${outfitIds.map((id) => `<button class="text-layout-card ${state.characterSheet.outfitStyle === id ? 'selected' : ''}" data-outfit-style="${id}"><img src="./images/samples/outfit/${type}/${id}.png" alt="${outfitLabels[id]}の服装例"><span>${outfitLabels[id]}</span></button>`).join('')}</div>`;
  const screens = [
    ['キャラクターの見本を作る', '<p>キャラクターの元になる画像を用意してください。最後にPromptと一緒にAIへ添付します。</p>'],
    ['どんなキャラクターを作りますか？', `<p>人物タイプを選んでください。通常の画像作成には表示されません。</p><div class="choice-grid">${[['male','男性'],['female','女性'],['unspecified','その他・指定しない']].map(([id,label]) => `<button class="choice ${state.characterSheet.characterType === id ? 'selected' : ''}" data-character-type="${id}">${label}</button>`).join('')}</div>`],
    ['服装の雰囲気', `<p>キャラクターに合う服装を、見た目から選べます。<br>あとから変更できます。</p>${outfitCards(state.characterSheet.characterType)}`],
    ['キャラクター情報', `<p>分かるところだけでOKです。</p><div class="character-form">${[['name','名前（任意）'],['age','年齢イメージ'],['gender','性別表現（任意）'],['hair','髪型・髪色'],['eyes','目'],['outfit','具体的な服装（任意）'],['body','体型・身長イメージ'],['features','特徴'],['fixed','絶対に変えたくない特徴']].map(([key,label]) => `<label>${label}<input data-character-info="${key}" value="${escapeHtml(state.characterSheet.characterInfo[key])}"></label>`).join('')}</div>`],
    ['キャラクターシートの内容', '<p>全身・顔・表情・ディテールを1枚に整理します。</p><ul class="character-checklist"><li>全身：正面・斜め前・横・後ろ</li><li>顔：正面・斜め・横</li><li>表情：通常・笑顔・驚き・困る／悲しい</li><li>髪型・目・衣装・靴・アクセサリー</li></ul>'],
    ['使用する画像生成AI', `<div class="adapter-list">${[['generic','その他の画像生成AI','汎用プロンプト'],['chatgpt','ChatGPT','ChatGPTの画像生成向け'],['gemini','Gemini','Geminiの画像生成向け']].map(([id,label,desc]) => `<button aria-label="${label}" class="adapter ${state.characterSheet.adapter === id ? 'selected' : ''}" data-character-adapter="${id}"><strong>${label}</strong><small>${desc}</small></button>`).join('')}</div>`],
    ['キャラクターシートを作る準備ができました', `<div class="result-copy"><label for="character-result">完成したPrompt</label><textarea id="character-result" readonly>${escapeHtml(buildCharacterSheetPrompt(state.characterSheet, state.characterSheet.adapter))}</textarea><button class="copy-cta" id="character-copy">◎ コピーする</button><p class="next-guide">① Promptをコピー<br>② ChatGPT / Gemini等を開く<br>③ キャラクターの元画像を添付<br>④ Promptを貼り付けて生成<br>⑤ 完成したCharacter Sheetを保存</p><h2>キャラクターシートを使うとき</h2><p>完成したプロンプトを画像生成AIで使って、キャラクターシート画像を作成してください。</p><p>作成したキャラクターシート画像を、次に同じキャラクターで画像を作るときの基準画像（参考画像）として登録して使用します。</p><p class="hint">※このアプリでプロンプトを作成しただけでは、キャラクターシート画像は自動で登録されません。画像生成AIでキャラクターシートを生成したあと、完成した画像を基準画像として登録してください。</p></div>`]
  ];
  const [title, body] = screens[state.charStep];
  app.innerHTML = `<main class="shell"><header class="topbar"><a class="brand" href="./" aria-label="ホームへ"><span class="brand-mark">P</span><span><strong>Prompt Studio</strong><small>Character Sheet</small></span></a></header><div class="page-heading"><p class="kicker">CHARACTER / ${state.charStep + 1} / ${screens.length}</p><h1>${title}</h1></div><section class="character-screen" aria-live="polite">${body}</section><nav class="nav"><button class="secondary" id="character-back">← 戻る</button><button class="primary" id="character-next">${state.charStep === screens.length - 1 ? '通常画像作成へ' : '次へ →'}</button></nav></main>`;
  document.querySelectorAll('[data-character-info]').forEach((input) => input.addEventListener('input', (event) => { state.characterSheet.characterInfo[event.target.dataset.characterInfo] = event.target.value; }));
  document.querySelectorAll('[data-character-type]').forEach((button) => button.addEventListener('click', () => { state.characterSheet.characterType = button.dataset.characterType; state.characterSheet.outfitStyle = ''; renderCharacterFlow(); }));
  document.querySelectorAll('[data-outfit-style]').forEach((button) => button.addEventListener('click', () => { state.characterSheet.outfitStyle = button.dataset.outfitStyle; renderCharacterFlow(); }));
  document.querySelectorAll('[data-character-adapter]').forEach((button) => button.addEventListener('click', () => { state.characterSheet.adapter = button.dataset.characterAdapter; renderCharacterFlow(); }));
  $('#character-copy')?.addEventListener('click', async () => { await navigator.clipboard?.writeText(buildCharacterSheetPrompt(state.characterSheet, state.characterSheet.adapter)); $('#character-copy').textContent = 'コピーしました'; });
  $('#character-back').addEventListener('click', () => { if (state.charStep === 0) { state.charFlow = false; return render(); } state.charStep -= 1; renderCharacterFlow(); });
  $('#character-next').addEventListener('click', () => { if (state.charStep < screens.length - 1) { state.charStep += 1; renderCharacterFlow(); } else { state.charFlow = false; state.step = 0; render(); } });
}

function bind() {
  $('[data-character-start]')?.addEventListener('click', () => { state.charFlow = true; state.charStep = 0; renderCharacterFlow(); });
  document.querySelectorAll('[data-character-usage]').forEach((button) => button.addEventListener('click', () => { state.model.characterUsage = button.dataset.characterUsage; if (state.model.characterUsage !== 'with-character') { state.model.characterMode = 'free-character'; state.model.outfitStyle = ''; state.model.sceneryComposition ||= 'standard'; } saveDraft(); render(); }));
  document.querySelectorAll('[data-character-mode]').forEach((button) => button.addEventListener('click', () => { state.model.characterMode = button.dataset.characterMode; saveDraft(); render(); }));
  document.querySelectorAll('[data-outfit-style]').forEach((button) => button.addEventListener('click', () => { state.model.outfitStyle = button.dataset.outfitStyle; saveDraft(); render(); }));
  document.querySelectorAll('[data-scenery-composition]').forEach((button) => button.addEventListener('click', () => { state.model.sceneryComposition = button.dataset.sceneryComposition; saveDraft(); render(); }));
  document.querySelectorAll('[data-flow-step]').forEach((button) => button.addEventListener('click', () => { const target = Number(button.dataset.flowStep); if (target === 0 || state.model.subject.trim() || target <= state.step) { state.step = target; render(); } }));
  $('#subject')?.addEventListener('input', (e) => { state.model.subject = e.target.value; saveDraft(); });
  document.querySelectorAll('.card').forEach((card) => card.addEventListener('click', () => { state.model[steps[state.step]] = card.dataset.id; render(); }));
  document.querySelectorAll('[data-adjustment]').forEach((input) => input.addEventListener('input', (e) => { state.model.adjustments[e.target.dataset.adjustment] = Number(e.target.value); saveDraft(); }));
  document.querySelectorAll('[data-negative]').forEach((input) => input.addEventListener('change', (e) => { const id = e.target.dataset.negative; state.model.negative = e.target.checked ? [...new Set([...state.model.negative, id])] : state.model.negative.filter((x) => x !== id); saveDraft(); }));
  document.querySelectorAll('[data-text-enabled]').forEach((button) => button.addEventListener('click', () => { state.model.textOverlay.enabled = button.dataset.textEnabled === 'true'; if (state.model.textOverlay.enabled) state.model.negative = state.model.negative.filter((id) => id !== 'text'); saveDraft(); render(); }));
  $('#text-content')?.addEventListener('input', (e) => { state.model.textOverlay.content = e.target.value; saveDraft(); });
  document.querySelectorAll('[data-text-style]').forEach((button) => button.addEventListener('click', () => { state.model.textOverlay.style = button.dataset.textStyle; saveDraft(); render(); }));
  document.querySelectorAll('[data-text-layout]').forEach((button) => button.addEventListener('click', () => { state.model.textOverlay.layout = button.dataset.textLayout; saveDraft(); render(); }));
  document.querySelectorAll('[data-text-position]').forEach((button) => button.addEventListener('click', () => { state.model.textOverlay.position = button.dataset.textPosition; saveDraft(); render(); }));
  document.querySelectorAll('[data-text-size]').forEach((button) => button.addEventListener('click', () => { state.model.textOverlay.size = button.dataset.textSize; saveDraft(); render(); }));
  $('[data-avoid-overlap]')?.addEventListener('change', (e) => { state.model.textOverlay.avoidSubjectOverlap = e.target.checked; saveDraft(); });
  document.querySelectorAll('[data-adapter]').forEach((button) => button.addEventListener('click', () => { state.model.adapter = button.dataset.adapter; saveDraft(); render(); }));
  $('#back')?.addEventListener('click', () => { state.step = Math.max(0, state.step - 1); render(); });
  $('#next')?.addEventListener('click', next);
  $('#copy')?.addEventListener('click', async () => { await navigator.clipboard?.writeText(state.result); $('#copy').textContent = 'コピーしました'; });
  $('#save')?.addEventListener('click', saveHistory);
  document.querySelectorAll('[data-favorite]').forEach((button) => button.addEventListener('click', () => toggleFavorite(button.dataset.favorite)));
  $('#backup')?.addEventListener('click', async () => { const blob = new Blob([JSON.stringify(await exportData(), null, 2)], { type: 'application/json' }); const a = document.createElement('a'); a.href = URL.createObjectURL(blob); a.download = 'image-prompt-maker-backup.json'; a.click(); });
  $('#restore')?.addEventListener('change', async (e) => { try { const file = e.target.files?.[0]; if (!file) return; const payload = JSON.parse(await file.text()); await importData(payload); state.history = await getAll('history'); render(); alert('復元しました'); } catch (error) { console.error('Backup restore failed', error); alert('JSONを読み込めませんでした。'); } finally { e.target.value = ''; } });
}
async function next() { if (state.step === 0 && !state.model.subject.trim()) return alert('作りたいものを入力してください。'); if (state.step === 5 && !state.model.textOverlay.enabled) { state.step = 11; return render(); } if (state.step === 6 && !state.model.textOverlay.content.trim()) return alert('入れたい文字を入力してください。'); if (state.step === 11) { state.result = adaptPrompt(state.model, state.model.adapter); state.step = 12; state.history = await getAll('history'); render(); return; } if (state.step < steps.length - 1) { state.step += 1; return render(); } state.step = 0; state.model = createPromptModel(); render(); }
async function saveDraft() { await put('drafts', { id: 'current', updatedAt: new Date().toISOString(), model: state.model }); }
async function saveHistory() { const item = { id: crypto.randomUUID(), createdAt: new Date().toISOString(), prompt: state.result, model: state.model, favorite: false }; await put('history', item); await put('projects', { id: item.id, createdAt: item.createdAt, model: item.model, prompt: item.prompt }); state.history = await getAll('history'); render(); }
async function toggleFavorite(id) { const item = state.history.find((entry) => entry.id === id); if (!item) return; item.favorite = !item.favorite; await put('history', item); if (item.favorite) await put('favorites', { id, historyId: id, createdAt: new Date().toISOString() }); else await remove('favorites', id); state.history = await getAll('history'); render(); }
async function restoreDraft() { try { const drafts = await getAll('drafts'); if (drafts[0]?.model) state.model = createPromptModel(drafts[0].model); state.history = await getAll('history'); } catch (error) { console.error('Draft restore failed', error); } render(); }
restoreDraft();
